//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class follower
    {
        public int Id { get; set; }

        public int User_id { get; set; }

        public string Follower_name { get; set; }

        public int Follower_id { get; set; }
    }
}
